"use strict";
var th = {
    name: 'accessible surveys II',
    index: -80,
    desc: 'accessible surveys vivid',
    longDesc: 'contrasted version of accessible surveys',
    darkTheme: '_a14y_variant_dark',
    theme: {
        '--color-brand': '#7f5361',
        '--color-brand-rgb': '125, 82, 96',
        '--color-disabled-text': '#646464',
        '--color-secondary-text': '#555',
        '--md-sys-color-primary': '#5e2aff',
        '--md-sys-color-on-primary': '#ffffff',
        '--md-sys-color-primary-container': '#e6deff',
        '--md-sys-color-on-primary-container': '#190065',
        '--md-sys-color-secondary': '#625B71',
        '--md-sys-color-on-secondary': '#FFFFFF',
        '--md-sys-color-secondary-container': '#E8DEF8',
        '--md-sys-color-on-secondary-container': '#1D192B',
        '--md-sys-color-tertiary': '#ba005c',
        '--md-sys-color-on-tertiary': '#ffffff',
        '--md-sys-color-tertiary-container': '#ffd9e3',
        '--md-sys-color-on-tertiary-container': '#3f001b',
        '--md-sys-color-outline': '#79747E',
        '--md-sys-color-background': '#FFFBFE',
        '--md-sys-color-on-background': '#1C1B1F',
        '--md-sys-color-surface': '#FFFBFE',
        '--md-sys-color-on-surface': '#1C1B1F',
        '--md-sys-color-surface-variant': '#E7E0EC',
        '--md-sys-color-on-surface-variant': '#49454F',
        '--md-sys-color-inverse-surface': '#313033',
        '--md-sys-color-inverse-on-surface': '#F4EFF4',
        '--md-sys-color-primary-rgb': '64, 42, 255',
        '--md-sys-color-secondary-rgb': '98, 91, 113',
        '--md-sys-color-tertiary-rgb': '186, 0, 92',
        '--md-sys-color-on-primary-rgb': '255, 255, 255',
        '--md-sys-color-on-secondary-rgb': '255, 255, 255',
        '--md-sys-color-on-tertiary-rgb': '255, 255, 255',
        '--md-sys-color-background-rgb': '255, 251, 254',
        '--md-sys-color-surface-rgb': '255, 251, 254'
    }
};
export default th;

