"use strict";
var th = {
    name: 'accessible surveys',
    index: -80,
    desc: 'accessible surveys',
    longDesc: 'accessible surveys',
    darkTheme: '_a14y_dark',
    theme: {
        '--color-brand': '#7f5361',
        '--color-brand-rgb': '125, 82, 96',
        '--color-disabled-text': '#646464',
        '--color-secondary-text': '#555',
        '--md-sys-color-primary': '#6750A4',
        '--md-sys-color-on-primary': '#FFFFFF',
        '--md-sys-color-primary-container': '#EADDFF',
        '--md-sys-color-on-primary-container': '#21005D',
        '--md-sys-color-secondary': '#625B71',
        '--md-sys-color-on-secondary': '#FFFFFF',
        '--md-sys-color-secondary-container': '#E8DEF8',
        '--md-sys-color-on-secondary-container': '#1D192B',
        '--md-sys-color-tertiary': '#7D5260',
        '--md-sys-color-on-tertiary': '#FFFFFF',
        '--md-sys-color-tertiary-container': '#FFD8E4',
        '--md-sys-color-on-tertiary-container': '#31111D',
        '--md-sys-color-outline': '#79747E',
        '--md-sys-color-background': '#FFFBFE',
        '--md-sys-color-on-background': '#1C1B1F',
        '--md-sys-color-surface': '#FFFBFE',
        '--md-sys-color-on-surface': '#1C1B1F',
        '--md-sys-color-surface-variant': '#E7E0EC',
        '--md-sys-color-on-surface-variant': '#49454F',
        '--md-sys-color-inverse-surface': '#313033',
        '--md-sys-color-inverse-on-surface': '#F4EFF4',
        '--md-sys-color-primary-rgb': '103, 80, 164',
        '--md-sys-color-secondary-rgb': '98, 91, 113',
        '--md-sys-color-tertiary-rgb': '125, 82, 96',
        '--md-sys-color-on-primary-rgb': '255, 255, 255',
        '--md-sys-color-on-secondary-rgb': '255, 255, 255',
        '--md-sys-color-on-tertiary-rgb': '255, 255, 255',
        '--md-sys-color-background-rgb': '255, 251, 254',
        '--md-sys-color-surface-rgb': '255, 251, 254'
    }
};
export default th;

