import { type ThemeT } from './types';
const th: ThemeT = {
  name: 'alternative',
  index: -60,
  desc: 'alternative theme',
  longDesc: 'teal and yellow colors',
  darkTheme: '_tealYellow_dark',
  theme: {
    '--color-accent-rgb':'255, 214, 0',
    '--color-accent':'#ffd600',
    '--color-brand-rgb':'2, 131, 109',
    '--color-brand':'#02836d',
    '--color-outline':'#79747E',
    '--color-secondary-text':'#212121',
    '--color-disabled-text':'#646464',
    '--md-sys-color-primary':'#004d40',
    '--md-sys-color-primary-rgb':'0, 77, 64',
    '--md-sys-color-on-primary':'#ffffff',
    '--md-sys-color-on-primary-rgb':'255, 255, 255',
    '--md-sys-color-primary-container':'#7af8db',
    '--md-sys-color-on-primary-container':'#002019',
    '--md-sys-color-secondary':'#625B71',
    '--md-sys-color-secondary-rgb':'98, 91, 113',
    '--md-sys-color-on-secondary':'#FFFFFF',
    '--md-sys-color-on-secondary-rgb':'255, 255, 255',
    '--md-sys-color-secondary-container':'#E8DEF8',
    '--md-sys-color-on-secondary-container':'#1D192B',
    '--md-sys-color-tertiary':'#ffd600',
    '--md-sys-color-tertiary-rgb':'255, 214, 0',
    '--md-sys-color-on-tertiary':'#ffffff',
    '--md-sys-color-on-tertiary-rgb':'255, 255, 255',
    '--md-sys-color-tertiary-container':'#eaea00',
    '--md-sys-color-on-tertiary-container':'#1d1d00',
    '--md-sys-color-background':'#FFFBFE',
    '--md-sys-color-on-background':'#1C1B1F',
    '--md-sys-color-surface':'#FFFBFE',
    '--md-sys-color-on-surface':'#1C1B1F',
    '--md-sys-color-inverse-surface':'#313033',
    '--md-sys-color-inverse-on-surface':'#F4EFF4',
    '--md-sys-color-surface-variant':'#E7E0EC',
    '--md-sys-color-on-surface-variant':'#49454F',

    '--md-sys-color-background-rgb': '255, 251, 254',
    '--md-sys-color-surface-rgb': '255, 251, 254',
  },
}

export default th
