export const databases = [
  // ['iowa', 'Iowa'],
  // ['queretaro', 'Queretaro'],
  ['losangeles', 'Los Angeles'],
  ['saltlakecity', 'Salt Lake City'],
  ['lasvegas', 'Las Vegas'],
  ['montreal', 'Montreal'],
  ['toronto', 'Toronto'],
  ['phoenix', 'Phoenix'],
  ['southcarolina', 'South Carolina'],
  ['northernvirginia', 'Northern Virginia'],
  ['columbus', 'Columbus'],
  ['dallas', 'Dallas'],
  ['santiago', 'Santiago'],
  ['saopaulo', 'Sao Paulo'],
  ['london', 'London'],
  ['belgium', 'Belgium'],
  ['netherlands', 'Netherlands'],
  ['milan', 'Milan'],
  ['madrid', 'Madrid'],
  ['paris', 'Paris'],
  ['turin', 'Turin'],
  ['berlin', 'Berlin'],
  ['frankfurt', 'Frankfurt'],
  ['finland', 'Finland'],
  ['stockholm', 'Stockholm'],
  ['warsaw', 'Warsaw'],
  ['doha', 'Doha'],
  ['damman', 'Damman'],
  ['telaviv', 'Tel Aviv'],
  ['mumbai', 'Mumbai'],
  ['delhi', 'Delhi'],
  ['singapore', 'Singapore'],
  ['jakarta', 'Jakarta'],
  ['hongkong', 'Hong Kong'],
  ['taiwan', 'Taiwan'],
  ['tokyo', 'Tokyo'],
  ['osaka', 'Osaka'],
  ['seoul', 'Seoul'],
  ['sydney', 'Sydney'],
  ['melbourne', 'Melbourne'],
  ['johannesburg', 'Johannesburg'],
] as const;

export const databaseMulti = [
  [ 'multi-eu-eur3', 'Europe', 'replicated in Belgium, Netherlands, Finland'],
  [ 'multi-us-nam5', 'US', 'replicated in multiple locations across the US'],

]

export type DatabaseIdT = (typeof databases)[number][0] | (typeof databaseMulti)[number][0];